version: '3.8'

services:
   redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"  # Kafka API
      - "9644:9644"  # Admin API
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - pawpal-net

networks:
  pawpal-net:
    external: true

volumes:
  redpanda-data:
    
      
