version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: packages/pawpal-auth/Dockerfile
    volumes:
      - ../../packages/pawpal-auth/src/./:/usr/src/app/packages/pawpal-auth/src
      - ../../packages/pawpal-shared/./:/usr/src/app/packages/pawpal-shared
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db
    env_file: ../../packages/pawpal-auth/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: pnpm --filter ./packages/pawpal-auth start:api:docker

  db:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_UI_PORT-15672:15672}
    environment: 
      RABBITMQ_DEFAULT_USER: guest # Default username (change in production)
      RABBITMQ_DEFAULT_PASS: guest # Default password (change in production)
      RABBITMQ_ERLANG_COOKIE: secretcookie
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    
      
