components:
  schemas:
    products:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
        description:
          type: string
        category: 
          $ref: '#/components/schemas/productCategory'
        ingredients:
          type: array
          items: 
            $ref: '#/components/schemas/productIngredients'
        images: 
          type: array
          items: 
            $ref: '#/components/schemas/productImages'
        meta_data:
          type: object
          additionalProperties: true
        prices: 
          type: array
          items:
            $ref: '#/components/schemas/productPrices'
