version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: packages/pawpal-store/Dockerfile
    volumes:
      - ../../packages/pawpal-store/src/./:/usr/src/app/packages/pawpal-store/src
      - ../../packages/pawpal-shared/./:/usr/src/app/packages/pawpal-shared
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db
    env_file: ../../packages/pawpal-store/.env
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: pnpm --filter ./packages/pawpal-store start:api:docker

  db:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # Increase db max connections to 200
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB"] 
    
      
